// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplyManagementAPI.Data;

#nullable disable

namespace SupplyManagementAPI.Migrations
{
    [DbContext(typeof(SupplyManagementDbContext))]
    partial class SupplyManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SupplyManagementAPI.Models.Account", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("ExpiredTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expired_time");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<int>("Otp")
                        .HasColumnType("int")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<Guid>("RoleGuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_guid");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Guid");

                    b.HasIndex("RoleGuid");

                    b.ToTable("tb_m_accounts");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("6501a19f-1b9b-49ab-adeb-9d5d4631ea11"),
                            ExpiredTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsUsed = false,
                            Otp = 0,
                            Password = "$2a$12$uVJ1rqZNoFlM5yMA8huJQecDgsY/YUXejKW1UWkf6B46tab6rEnrC",
                            RoleGuid = new Guid("439853e6-0c0e-4651-8bb0-c22042fcb102"),
                            Status = 1
                        },
                        new
                        {
                            Guid = new Guid("f5cd1f99-c521-4dc2-8e31-959f66d5c076"),
                            ExpiredTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsUsed = false,
                            Otp = 0,
                            Password = "$2a$12$Q8JXjmkY83aCdnjlFNI0SeLjGB6J6PcX0iymKnA0MV8Ku3mpAlYOq",
                            RoleGuid = new Guid("184f2911-682c-41d1-aafd-f45958d57ddd"),
                            Status = 1
                        });
                });

            modelBuilder.Entity("SupplyManagementAPI.Models.Company", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("guid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext")
                        .HasColumnName("foto");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone_number");

                    b.HasKey("Guid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("tb_m_company");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("6501a19f-1b9b-49ab-adeb-9d5d4631ea11"),
                            Address = "null",
                            CreatedDate = new DateTime(2023, 12, 30, 11, 48, 17, 254, DateTimeKind.Local).AddTicks(7378),
                            Email = "admin@mail.com",
                            Foto = "null",
                            Name = "Admin",
                            PhoneNumber = "00000"
                        },
                        new
                        {
                            Guid = new Guid("f5cd1f99-c521-4dc2-8e31-959f66d5c076"),
                            Address = "null",
                            CreatedDate = new DateTime(2023, 12, 30, 11, 48, 17, 254, DateTimeKind.Local).AddTicks(7405),
                            Email = "manager@mail.com",
                            Foto = "nul",
                            Name = "Manager Logistic",
                            PhoneNumber = "11111"
                        });
                });

            modelBuilder.Entity("SupplyManagementAPI.Models.Person", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Guid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tb_m_persons");
                });

            modelBuilder.Entity("SupplyManagementAPI.Models.Role", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name");

                    b.HasKey("Guid");

                    b.ToTable("tb_m_roles");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("439853e6-0c0e-4651-8bb0-c22042fcb102"),
                            Name = "admin"
                        },
                        new
                        {
                            Guid = new Guid("184f2911-682c-41d1-aafd-f45958d57ddd"),
                            Name = "manager"
                        },
                        new
                        {
                            Guid = new Guid("17b81a69-828f-4963-b4d6-5d3130dc114a"),
                            Name = "vendor"
                        });
                });

            modelBuilder.Entity("SupplyManagementAPI.Models.Vendor", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)")
                        .HasColumnName("guid");

                    b.Property<string>("BidangUsaha")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bidang_usaha");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("JenisPerusahaan")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("jenis_perusahaan");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<int?>("StatusVendor")
                        .HasColumnType("int")
                        .HasColumnName("status_vendor");

                    b.HasKey("Guid");

                    b.ToTable("tb_m_vendor");
                });

            modelBuilder.Entity("SupplyManagementAPI.Models.Account", b =>
                {
                    b.HasOne("SupplyManagementAPI.Models.Company", "Company")
                        .WithOne("Account")
                        .HasForeignKey("SupplyManagementAPI.Models.Account", "Guid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyManagementAPI.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SupplyManagementAPI.Models.Vendor", b =>
                {
                    b.HasOne("SupplyManagementAPI.Models.Company", "Company")
                        .WithOne("Vendor")
                        .HasForeignKey("SupplyManagementAPI.Models.Vendor", "Guid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SupplyManagementAPI.Models.Company", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SupplyManagementAPI.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
